#!bin/bash
#This is not the actual bash script used. However, all code is bash based. Read comments for full instruction. Works on ubuntu trusty and BBB rev C-debian. remember to chmod u+x all scripts.

#Step 1
  #make file startBBB, put in LAPTOP/bin to invoke anywhere.

  sudo iptables -A POSTROUTING -t nat -j MASQUERADE
  sudo echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward > /dev/null
  ssh 192.168.7.2 -l root




#Step 2 
  #put into file named internetinit
  #put file into BBB/~

  /sbin/route add default gw 192.168.7.1
  echo "nameserver 8.8.8.8" >> /etc/resolv.conf
  ping -c 2 google.com
  clear
  if [ $? == "0" ]
  then
    echo CONNECTED
  else
    echo FAILURE
  fi
  
#Step 3
  #append "./internetinit" to the end of BBB/~/.bashrc
  #this will run internetinit after you ssh into BBB but before the root@BBB session starts
    

#Step 4 - YOURE CONNECTED
  #calling startBBB anywhere in your laptop terminal will create a root@BBB session with full internet capabilities


